# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siparis_gecmisi_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class siparis_gecmisi(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(901, 460)
        mainWindow.setMinimumSize(QtCore.QSize(901, 460))
        mainWindow.setMaximumSize(QtCore.QSize(901, 460))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.order_history = QtWidgets.QTableWidget(self.centralwidget)
        self.order_history.setGeometry(QtCore.QRect(10, 150, 881, 291))
        self.order_history.setObjectName("order_history")
        self.order_history.setColumnCount(8)
        self.order_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_history.setHorizontalHeaderItem(7, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 871, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(46)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.customer_info = QtWidgets.QLineEdit(self.centralwidget)
        self.customer_info.setGeometry(QtCore.QRect(10, 111, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.customer_info.setFont(font)
        self.customer_info.setObjectName("customer_info")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(220, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.error_handling = QtWidgets.QLabel(self.centralwidget)
        self.error_handling.setGeometry(QtCore.QRect(350, 110, 541, 31))
        self.error_handling.setText("")
        self.error_handling.setObjectName("error_handling")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Sipariş Geçmişi"))
        item = self.order_history.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Ödeme"))
        item = self.order_history.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Tarih-Saat"))
        item = self.order_history.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Müşteri Bilgisi"))
        item = self.order_history.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Tutar"))
        item = self.order_history.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Kart Numarası"))
        item = self.order_history.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Sipariş "))
        item = self.order_history.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Notlar"))
        item = self.order_history.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Sil"))
        self.label.setText(_translate("mainWindow", "SİPARİŞ GEÇMİŞİ"))
        self.customer_info.setPlaceholderText(_translate("mainWindow", "Lütfen Müşteri Bilgisini Giriniz"))
        self.pushButton_search.setText(_translate("mainWindow", "ARA"))
